name: ðŸ—ï¸ Build on CI

on:
  push:
    branches: ['master']

jobs:
  build-mac:
    name: ï£¿ Build Mac
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3

      - name: Configure variables
        run: |
          XC_ARCHIVE=${RUNNER_TEMP}/Cider.xcarchive
          echo "XC_ARCHIVE=${XC_ARCHIVE}" >> $GITHUB_ENV

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew dependencies
        run: brew bundle

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Prepare Yarn
        run: export YARN_ENABLE_IMMUTABLE_INSTALLS=false

      - name: Install CiderWebAuth's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderWebAuth/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Install CiderPlaybackAgent's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderPlaybackAgent/Web Scripts/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Install CiderDevUtils's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderDevUtils/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Setup Rust Toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
          source "$HOME/.cargo/env"
          rustup +nightly target add aarch64-apple-darwin x86_64-apple-darwin
          rustup default nightly

      - name: Install cargo-lipo from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-lipo

      - name: Build JS modules
        run: task build:all-js

      - name: Fetch Google API credentials
        run: task fetch:google-services

      - name: Build Discord RPC module
        run: task build:discord-rpc-lib

      - name: Build NativeUtils module
        run: task build:native-utils-lib

      - name: Build XCArchive
        run: |
          task archive:xc XC_ARCHIVE="$XC_ARCHIVE"

      - name: Build DMG
        run: |
          task archive:build-app-bundle XC_ARCHIVE="$XC_ARCHIVE"
          task build:dmg

      - name: Compress artifacts
        working-directory: ${{ runner.temp }}
        run: zip -r Cider.xcarchive.zip Cider.xcarchive/**/*

      - name: Upload XCArchive
        uses: actions/upload-artifact@v3
        with:
          name: Cider XCArchive (Compressed)
          path: ${{ env.XC_ARCHIVE }}.zip
          retention-days: 1

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: Cider.dmg
          path: ${{ runner.temp }}/dest/Cider.dmg
          retention-days: 1

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "deploy"
          description: "Build Cider for macOS"
          url: "https://github.com/ciderapp/project2-swiftui/actions"
          username: GitHub Actions
          avatar_url: "https://avatars.githubusercontent.com/u/87914859?s=200&v=4"
