name: ðŸ—ï¸ Build on CI

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build-mac:
    name: ï£¿ Build Mac
    runs-on: [self-hosted, macOS, ARM64]
    env:
      KEYCHAIN: job-${{ github.job }}-${{ github.run_id	}}-${{ github.run_number }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure variables
        run: |
          XC_ARCHIVE=${RUNNER_TEMP}/Cider.xcarchive
          echo "XC_ARCHIVE=${XC_ARCHIVE}" >> $GITHUB_ENV

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew dependencies
        run: brew bundle

      # - name: Install P12 Key
      #   uses: apple-actions/import-codesign-certs@v2
      #   with: 
      #     keychain: ${{ env.KEYCHAIN }}
      #     p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
      #     p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Install certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATES_P12 }}
          P12_PASSWORD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Install provisioning profile
        env:
          MACOS_PROVISIONING_PROFILE_UUID: ${{ secrets.MACOS_PROVISIONING_PROFILE_UUID }}
          MACOS_PROVISIONING_PROFILE_B64: ${{ secrets.MACOS_PROVISIONING_PROFILE_B64 }}
        run: |
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo -n $MACOS_PROVISIONING_PROFILE_B64 | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/$MACOS_PROVISIONING_PROFILE_UUID.provisionprofile"

      - name: Update SPM Packages
        uses: GetSidetrack/action-xcodeproj-spm-update@main
        with:
          scheme: 'Cider - Release'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Prepare Yarn
        run: export YARN_ENABLE_IMMUTABLE_INSTALLS=false

      - name: Install CiderWebAuth's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderWebAuth/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Install CiderPlaybackAgent's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderPlaybackAgent/Web Scripts/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Install CiderDevUtils's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderDevUtils/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Setup Rust Toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
          source "$HOME/.cargo/env"
          rustup +nightly target add aarch64-apple-darwin x86_64-apple-darwin
          rustup default nightly
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Install cargo-lipo from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-lipo

      - name: Build JS modules
        run: task build:all-js

      - name: Fetch Google API credentials
        run: task fetch:google-services

      - name: Build NativeUtils module
        run: task build:native-utils-lib

      - name: Build XCArchive
        run: |
          task archive:xc XC_ARCHIVE="$XC_ARCHIVE"

      - name: Build DMG
        run: |
          task archive:build-app-bundle XC_ARCHIVE="$XC_ARCHIVE"
          task build:dmg

      - name: Compress artifacts
        working-directory: ${{ runner.temp }}
        run: zip -r Cider.xcarchive.zip Cider.xcarchive/**/*

      - name: Upload XCArchive
        uses: actions/upload-artifact@v3
        with:
          name: Cider XCArchive (Compressed)
          path: ${{ env.XC_ARCHIVE }}.zip
          retention-days: 1

      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: Cider.dmg
          path: ${{ runner.temp }}/dest/Cider.dmg
          retention-days: 1

      - name: Delete keychain
        if: always() # Always run this step to ensure the keychain is properly disposed of
        run: |
          # security delete-keychain "${{ env.KEYCHAIN }}".keychain
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "deploy"
          description: "Build Cider for macOS"
          url: "https://github.com/ciderapp/project2-swiftui/actions"
          username: GitHub Actions
          avatar_url: "https://avatars.githubusercontent.com/u/87914859?s=200&v=4"
