name: üèóÔ∏è Build on CI

on:
  push:
    branches: ['master']

jobs:
  build-mac:
    name: Ô£ø Build Mac
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew dependencies
        run: brew bundle

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Prepare Yarn
        run: export YARN_ENABLE_IMMUTABLE_INSTALLS=false

      - name: Install CiderWebAuth's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderWebAuth/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Install CiderPlaybackAgent's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderPlaybackAgent/Web Scripts/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Install CiderDevUtils's dependencies with Yarn
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: 'CiderDevUtils/'
          enable-corepack: true
          cache-node-modules: true
          cache-install-state: true

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: nightly
          target: x86_64-apple-darwin

      - name: Install cargo-hack from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-lipo

      - name: Build JS modules
        run: task build:all-js

      - name: Fetch Google API credentials
        run: task fetch:google-services

      - name: Build Discord RPC module
        run: task build:discord-rpc-lib

      - name: Build NativeUtils module
        run: task build:native-utils-lib

      - name: Build Release Archive
        run: task archive:xc XC_ARCHIVE=$RUNNER_TEMP/Cider.xcarchive

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cider XCArchive
          path: $RUNNER_TEMP/Cider.xcarchive
